In [1]:
df = pd.read_csv("archive/Combined_dataset.csv")

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("archive/Combined_dataset.csv")

In [ ]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [ ]:
import pandas as pd

In [ ]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [ ]:
df.shape

(1000, 24)

In [ ]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [ ]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [ ]:
df.fillna(0, inplace=True)

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [ ]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna("Unknown")
    else:
        df[col] = df[col].fillna(0)

In [ ]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [ ]:
df[df['final_price'] > 1000]

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [ ]:
df['final_price'].fillna(0, inplace=True)

C:\Users\Zaid Pathan\AppData\Local\Temp\ipykernel_20744\3667849902.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['final_price'].fillna(0, inplace=True)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: final_price, Length: 1000, dtype: float64

In [ ]:
df[df['final_price'] > 1000]

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [ ]:
df[['title', 'final_price', 'rating', 'seller_name']]

              title  final_price  rating     seller_name
0       Lino Perros          NaN     3.8               0
1    Tommy Hilfiger          NaN     4.5               0
2             Lavie          NaN     4.4               0
3            F Gear          NaN     4.4               0
4         MYTRIDENT          NaN     4.7               0
..              ...          ...     ...             ...
995           KREDO          NaN     3.5               0
996           GUESS          NaN     5.0               0
997        GIORDANO          NaN     2.8               0
998        Fastrack          NaN     4.3  Tru███m R███il
999         BOLDFIT          NaN     3.8               0

[1000 rows x 4 columns]

In [ ]:
df['quantity'] = 1

In [ ]:
df['total_amount'] = df['final_price'] * df['quantity']

In [ ]:
df.to_csv("cleaned_shopping.csv", index=False)

In [ ]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,NaN,INR,http://assets.myntassets.com/assets/images/837...,...,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,NaN,INR,http://assets.myntassets.com/assets/images/913...,...,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,NaN,INR,http://assets.myntassets.com/assets/images/176...,...,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,NaN,INR,http://assets.myntassets.com/assets/images/137...,...,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,NaN,INR,http://assets.myntassets.com/assets/images/pro...,...,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,NaN

In [ ]:
df.tail()

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("archive/Combined_dataset.csv")

In [ ]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [ ]:
df.shape

In [ ]:
df.shape

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("archive/Combined_dataset.csv")

In [ ]:
df.head()

In [ ]:
df.tail()

In [2]:
df.tail()

NameError: name 'df' is not defined

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("archive/Combined_dataset.csv")

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
df.shape

(1000, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [10]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [11]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna("Unknown")
    else:
        df[col] = df[col].fillna(0)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [15]:
df['final_price'].fillna(0, inplace=True)

C:\Users\Zaid Pathan\AppData\Local\Temp\ipykernel_13768\3667849902.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['final_price'].fillna(0, inplace=True)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: final_price, Length: 1000, dtype: float64

In [16]:
df[df['final_price'] > 1000]

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [17]:
df[['title', 'final_price', 'rating', 'seller_name']]

              title  final_price  rating     seller_name
0       Lino Perros          NaN     3.8               0
1    Tommy Hilfiger          NaN     4.5               0
2             Lavie          NaN     4.4               0
3            F Gear          NaN     4.4               0
4         MYTRIDENT          NaN     4.7               0
..              ...          ...     ...             ...
995           KREDO          NaN     3.5               0
996           GUESS          NaN     5.0               0
997        GIORDANO          NaN     2.8               0
998        Fastrack          NaN     4.3  Tru███m R███il
999         BOLDFIT          NaN     3.8               0

[1000 rows x 4 columns]

In [18]:
df['quantity'] = 1

In [19]:
df['total_amount'] = df['final_price'] * df['quantity']

In [20]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,NaN,INR,http://assets.myntassets.com/assets/images/837...,...,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,NaN,INR,http://assets.myntassets.com/assets/images/913...,...,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,NaN,INR,http://assets.myntassets.com/assets/images/176...,...,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,NaN,INR,http://assets.myntassets.com/assets/images/137...,...,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,NaN,INR,http://assets.myntassets.com/assets/images/pro...,...,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,NaN

In [22]:
df['final_price'].fillna(0, inplace=True)

C:\Users\Zaid Pathan\AppData\Local\Temp\ipykernel_13768\3667849902.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['final_price'].fillna(0, inplace=True)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: final_price, Length: 1000, dtype: float64

In [21]:
df.to_csv("cleaned2_shopping.csv", index=False)

In [23]:
df['total_amount'] = df['final_price'] * df['quantity']

# Summary

- Loaded the shopping dataset using Pandas
- Explored the dataset using head(), tail(), shape(), columns(), and info()
- Checked and handled missing values
- Checked and removed duplicate rows
- Filtered products based on final_price
- Selected important columns
- Created quantity and total_amount columns
- Saved cleaned dataset as cleaned_shopping.csv

In [24]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,NaN,INR,http://assets.myntassets.com/assets/images/837...,...,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,NaN,INR,http://assets.myntassets.com/assets/images/913...,...,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,NaN,INR,http://assets.myntassets.com/assets/images/176...,...,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,NaN,INR,http://assets.myntassets.com/assets/images/137...,...,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,NaN,INR,http://assets.myntassets.com/assets/images/pro...,...,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,NaN

In [25]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [26]:
df['final_price'] = df['final_price'].fillna(0)

In [27]:
df[df['final_price'] > 1000]

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category, quantity, total_amount]
Index: []

[0 rows x 26 columns]

In [28]:
df[['title', 'final_price', 'rating', 'seller_name']]

              title  final_price  rating     seller_name
0       Lino Perros          0.0     3.8               0
1    Tommy Hilfiger          0.0     4.5               0
2             Lavie          0.0     4.4               0
3            F Gear          0.0     4.4               0
4         MYTRIDENT          0.0     4.7               0
..              ...          ...     ...             ...
995           KREDO          0.0     3.5               0
996           GUESS          0.0     5.0               0
997        GIORDANO          0.0     2.8               0
998        Fastrack          0.0     4.3  Tru███m R███il
999         BOLDFIT          0.0     3.8               0

[1000 rows x 4 columns]

In [29]:
df['quantity'] = 1

In [30]:
df['total_amount'] = df['final_price'] * df['quantity']

In [31]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,0.0,INR,http://assets.myntassets.com/assets/images/837...,...,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,0.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,0.0,INR,http://assets.myntassets.com/assets/images/913...,...,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,0.0,INR,http://assets.myntassets.com/assets/images/176...,...,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,0.0,INR,http://assets.myntassets.com/assets/images/137...,...,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,0.0,INR,http://assets.myntassets.com/assets/images/pro...,...,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,0.0

In [32]:
df['quantity'] = 1

In [33]:
df['total_amount'] = df['initial_price'] * df['quantity']

In [34]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,0.0,INR,http://assets.myntassets.com/assets/images/837...,...,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,3995
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,0.0,INR,http://assets.myntassets.com/assets/images/913...,...,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2899
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,0.0,INR,http://assets.myntassets.com/assets/images/176...,...,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2999
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,0.0,INR,http://assets.myntassets.com/assets/images/137...,...,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,1675
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,0.0,INR,http://assets.myntassets.com/assets/images/pro...,...,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,2899

In [35]:
df.to_csv("cleaned2_shopping.csv", index=False)

In [36]:
df.to_csv("cleaned_shopping.csv", index=False)

# Summary

- Loaded the shopping dataset using Pandas
- Explored the dataset using head(), tail(), shape(), columns(), and info()
- Checked and handled missing values
- Checked and removed duplicate rows
- Filtered products based on final_price
- Selected important columns
- Created quantity and total_amount columns
- Saved cleaned dataset as cleaned_shopping.csv